dist: trusty

os:
  - linux

language: perl6

perl6:
  - latest

install:
  - rakudobrew build-panda
  - panda --notests installdeps .
  - panda install git://github.com/frithnanth/perl6-Archive-Libarchive-Raw

script:
  - perl6 -MPanda::Builder -e 'Panda::Builder.build(~$*CWD)'
  - PERL6LIB=$PWD/lib PERL6_LIBARCHIVE_LIB=libarchive.so.13 prove -e perl6 -vr t/
